"""empty message

Revision ID: 7f1e5aa31080
Revises: 
Create Date: 2024-02-17 21:35:55.012827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f1e5aa31080'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('costOfInventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity_to_add', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('price_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['price_id'], ['prices.id'], name=op.f('fk_costOfInventory_price_id_prices')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_costOfInventory_product_id_products')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('price_id', sa.Integer(), nullable=True),
    sa.Column('cost_of_inventory_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cost_of_inventory_id'], ['costOfInventory.id'], name=op.f('fk_inventory_cost_of_inventory_id_costOfInventory')),
    sa.ForeignKeyConstraint(['price_id'], ['prices.id'], name=op.f('fk_inventory_price_id_prices')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_product_id_products')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_cost', sa.Float(), nullable=True),
    sa.Column('customer_cost', sa.Float(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_prices_product_id_products')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price_id', sa.Integer(), nullable=True),
    sa.Column('inventory_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], name=op.f('fk_products_inventory_id_inventory')),
    sa.ForeignKeyConstraint(['price_id'], ['prices.id'], name=op.f('fk_products_price_id_prices')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customerOrders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('data_ordered', sa.Date(), nullable=True),
    sa.Column('fullfilled', sa.Boolean(), nullable=True),
    sa.Column('date_fullfulled', sa.Date(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_customerOrders_product_id_products')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('customer_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_order_id'], ['customerOrders.id'], name=op.f('fk_customers_customer_order_id_customerOrders')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gross_sales', sa.Float(), nullable=True),
    sa.Column('net_sales', sa.Float(), nullable=True),
    sa.Column('customer_order_id', sa.Integer(), nullable=True),
    sa.Column('innventory_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_order_id'], ['customerOrders.id'], name=op.f('fk_sales_customer_order_id_customerOrders')),
    sa.ForeignKeyConstraint(['innventory_id'], ['inventory.id'], name=op.f('fk_sales_innventory_id_inventory')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales')
    op.drop_table('customers')
    op.drop_table('customerOrders')
    op.drop_table('products')
    op.drop_table('prices')
    op.drop_table('inventory')
    op.drop_table('costOfInventory')
    # ### end Alembic commands ###
