"""empty message

Revision ID: d214b7e0d488
Revises: 
Create Date: 2024-02-18 11:42:19.082691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd214b7e0d488'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_cost', sa.Float(), nullable=True),
    sa.Column('customer_cost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_price_association',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('price_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['price_id'], ['prices.id'], name=op.f('fk_product_price_association_price_id_prices')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_price_association_product_id_products'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_price_association')
    op.drop_table('products')
    op.drop_table('prices')
    # ### end Alembic commands ###
